// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaddfwycowygakforhro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZGRmd3ljb3d5Z2FrZm9yaHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODQzMzEsImV4cCI6MjA3MjU2MDMzMX0.exxl8LRrKSVuTPMVGXRR-Uh-yWDITdAoL_gdrkpztQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});